platform :ios, '12.0'
workspace '../Runner.xcworkspace'

target 'Runner' do
  use_frameworks!
  
  # Flutter is in the parent directory
  pod 'Flutter', :path => '../Flutter'
  
  # Plugin Pods
  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
  
  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('../Flutter/Generated.xcconfig')
  if generated_xcode_build_settings['FLUTTER_ROOT'] != nil
    flutter_root = generated_xcode_build_settings['FLUTTER_ROOT']
    Dir.glob(File.join('.symlinks', 'plugins', '*.podspec')).each do |plugin|
      pod File.basename(plugin, '.podspec'), :path => plugin
    end
  end
end

# Parse generated KV file
def parse_KV_file(file)
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return {}
  end
  generated_key_values = {}
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) do |line|
    next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
    plugin = line.split('=')
    if plugin.length == 2
      podname = plugin[0].strip()
      path = plugin[1].strip()
      generated_key_values[podname] = path
    end
  end
  generated_key_values
end