// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-2vyQnC-N0c6S1rOi2EE16lb7-wbG2AY',
    appId: '1:325881326687:web:266f4990db70d9e392bfea',
    messagingSenderId: '325881326687',
    projectId: 'evently-dfe89',
    authDomain: 'evently-dfe89.firebaseapp.com',
    storageBucket: 'evently-dfe89.firebasestorage.app',
    measurementId: 'G-ZFQKXEELMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8E2hkR-fwNgZ5Su5xpA1i9Fl3-d5cOk0',
    appId: '1:325881326687:android:731c7931c845da2a92bfea',
    messagingSenderId: '325881326687',
    projectId: 'evently-dfe89',
    storageBucket: 'evently-dfe89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClDnxt-Ruqpias8ewvfN_qhPHQNLXP_pA',
    appId: '1:325881326687:ios:64725bb7a61e172892bfea',
    messagingSenderId: '325881326687',
    projectId: 'evently-dfe89',
    storageBucket: 'evently-dfe89.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClDnxt-Ruqpias8ewvfN_qhPHQNLXP_pA',
    appId: '1:325881326687:ios:64725bb7a61e172892bfea',
    messagingSenderId: '325881326687',
    projectId: 'evently-dfe89',
    storageBucket: 'evently-dfe89.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-2vyQnC-N0c6S1rOi2EE16lb7-wbG2AY',
    appId: '1:325881326687:web:baabec7341c6a80392bfea',
    messagingSenderId: '325881326687',
    projectId: 'evently-dfe89',
    authDomain: 'evently-dfe89.firebaseapp.com',
    storageBucket: 'evently-dfe89.firebasestorage.app',
    measurementId: 'G-11LH7ZD2K1',
  );
}
